import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from 'next/router';
import SpotifyPlaylists from '~/component/spotify';


import { api } from "~/utils/api";

const WebAppPage: NextPage = () => {
  const tokens = api.spotify.spotifyToken.useQuery().data;
  const auth_header = api.spotify.refreshToken.useQuery().data;


  return (
    <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex flex-col justify-center items-center">
          <h1 className="text-3xl font-bold">Welcome to Playlists</h1>  
          <div className="h-200 mx-5 text-center">
            {!!tokens &&
            tokens.access_token &&
            tokens.refresh_token &&
            auth_header ? (
              console.log(`access_token: ${tokens.access_token}`),
              console.log(`refresh_token: ${tokens.refresh_token}`),
              console.log(`auth_header: ${auth_header}`),
              <SpotifyPlaylists
                access_token={tokens.access_token}
                refresh_token={tokens.refresh_token}
                auth_header={auth_header}
              />
            ) : null}
        </div>
          
        </main>
    </>
  );
};

export default WebAppPage;

